apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-jobmanager
  namespace: flink
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/flink-jobmanager"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-taskmanager
  namespace: flink
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/flink-taskmanager"
