apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ingress-argocd-flink.yaml

# Allows applying across multiple namespaces
# Even though kustomization.yaml is in argocd namespace,
# the Ingresses themselves specify their own namespaces
