---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cdc-consumers
  namespace: cdc-consumers
  labels:
    app: cdc-consumers
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      component: cdc-consumer
  namespaceSelector:
    matchNames:
      - cdc-consumers
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_label_app]
          targetLabel: service
